// product category types
export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST"
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS"
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL"

export const CATEGORY_STATE_RESET = "CATEGORY_STATE_RESET"
export const CATEGORY_ERRORS_CLEAR = "CATEGORY_ERRORS_CLEAR"


export const ADMIN_ERRORS_CLEAR = "ADMIN_ERRORS_CLEAR"